[package]
name = "savefile-test"
version = "0.0.1"
authors = ["Anders Musikka <anders@andersmusikka.se>"]

[dependencies]
savefile = { path = "../savefile", features = ["size_sanity_checks"]}
savefile-derive = { path = "../savefile-derive" }
bit-vec = "0.5"
arrayvec="0.4"
smallvec="1.0"
byteorder="*"
rand="*"
parking_lot="*"
