[package]
name = "savefile"
version = "0.3.0"
authors = ["Anders Musikka <anders@andersmusikka.se>"]

exclude = [
    "*.bin"
]

description = "Simple, convenient, fast, versioned, binary serialization/deserialization library. Requires nightly as of 2019-12-15"

readme = "../README.md"

keywords = ["serialization", "deserialization"]

categories = ["encoding"]

license = "MIT/Apache-2.0"

travis-ci = { repository = "avl/savefile", branch = "master" }

[dependencies]
byteorder="1.2"
failure="0.1"
bit-vec="0.5"
arrayvec="0.4"
smallvec="0.6"
indexmap ="1.0"
parking_lot= { version = "0.5" }

[dev-dependencies]
savefile-derive = { path = "../savefile-derive", version="0.3.0" }







