[package]
name = "savefile"
version = "0.7.1"
authors = ["Anders Musikka <anders@andersmusikka.se>"]
documentation = "https://docs.rs/savefile/"
homepage = "https://github.com/avl/savefile/"

exclude = [
    "*.bin"
]

description = "Simple, convenient, fast, versioned, binary serialization/deserialization library. Requires nightly as of 2019-12-15"

readme = "../README.md"

keywords = ["serialization", "deserialization", "introspection"]

categories = ["encoding"]

license = "MIT/Apache-2.0"

[features]
# Enable this to reduce risk of crashing on corrupt input. Provides sanity checks for sizes of objects.
# This is mostly to be able to run fuzzers against the deserializers without them being guaranteed to easily find out-of-memory crashes.
size_sanity_checks = []

[dependencies]
byteorder="1.2"
failure="0.1"
bit-vec="0.6"
arrayvec="0.5"
smallvec="1.0"
indexmap ="1.0"
parking_lot = { version = "0.10" }
ring = "0.16.9"
rand="0.7"
bzip2 = "0.3.2"


[dev-dependencies]
savefile-derive = { path = "../savefile-derive", version="0.7.1" }







