[package]
name = "savefile"
version = "0.2.3"
authors = ["Anders Musikka <anders@andersmusikka.se>"]

exclude = [
    "*.bin"
]

description = "Simple, convenient, fast, versioned, binary serialization/deserialization library."

readme = "../README.md"

keywords = ["serialization", "deserialization"]

categories = ["encoding"]

license = "MIT/Apache-2.0"

travis-ci = { repository = "avl/savefile", branch = "master" }

[dependencies]
byteorder="1.2.1"
failure="0.1.1"

[dev-dependencies]
savefile-derive = { path = "../savefile-derive", version="0.2.3" }







