[package]
name = "diskstore"
version = "0.0.1"
authors = [ "anders@andersmusikka.se" ]

[lib]
path = "src/lib.rs"

[dependencies]
bit-vec="*"
arrayvec="*"
chrono = "0.4"
diskstore-derive = { path = "diskstore-derive" }
byteorder="*"
