[package]
name = "savefile-derive"
version = "0.2.10"
authors = ["Anders Musikka <anders@andersmusikka.se>"]

description = "Custom derive macros for savefile crate - simple, convenient, fast, versioned, binary serialization/deserialization library."

readme = "../README.md"

keywords = ["serialization", "deserialization"]

categories = ["encoding"]

license = "MIT/Apache-2.0"

travis-ci = { repository = "avl/savefile", branch = "master" }

[lib]
proc-macro = true

[dependencies]
quote = "0.6"
syn = "0.14"
proc-macro2 = { version = "0.4", features = ["nightly"] }


